### ISSUE TITLE
Rolling on wand shows main hand weapon as current item

### ISSUE THREAD

**Issue by justinrusso** [evil-morfar/RCLootCouncil_Classic#1]
When rolling on a wand, the loot council sees the roller's main hand weapon to compare against.

Version: 2.13.1

**Comment by evil-morfar** [comment]
Thanks for your report. Will be fixed next update.

**Comment by evil-morfar** [comment]
fc8222f440918610cd7dd09ca01924c3a74a52f5

**Comment by evil-morfar** [comment]
Fixed in v0.0.2.
