### ISSUE TITLE
Exports from /rc history point to www.wowhead.com instead of classic.wowhead.com

### ISSUE THREAD

**Issue by poptix** [evil-morfar/RCLootCouncil_Classic#12]
Exports from /rc history point to www.wowhead.com instead of classic.wowhead.com

For some items, this results in invalid links due to removed items.

**Comment by evil-morfar** [comment]
Thanks for bringing it to my attention - will be fixed next update.

**Comment by poptix** [comment]
Unfortunately it's now pointing to www.classic.wowhead.com, which redirects to www.wowhead.com and still shows retail items.

It should point to "classic.wowhead.com", no "www". 

Thanks again for your hard work. This addon is fantastic.
