### ISSUE TITLE
Roll vote option

### ISSUE THREAD

**Issue by HOYS** [evil-morfar/RCLootCouncil_Classic#15]
When deciding loot, sometimes it is a toss up between a few raiders as to who should receive the piece. I propose adding a new voting option for an entire item that allows for the item to go to a roll between all who have selected need for the item.

This could be implemented as either a button on the top of the voting frame next to disenchant or as a faux raid member.

I'm interested in helping create this functionality.

**Comment by evil-morfar** [comment]
So pretty much either of the [existing roll features](https://github.com/evil-morfar/RCLootCouncil2/wiki/Voting-Frame#right-click-menu)?
