### ISSUE TITLE
Custom Award Reason

### ISSUE THREAD

**Issue by ferrius94** [evil-morfar/RCLootCouncil_Classic#17]
Greetings Morfar

Thanks for your work porting this to Classic, it's significantly sped up our loot process.

Recently, we've had more and more loot being given out for very specific reasons - hence our button options, or other preset options (disenchant, etc.) - are no longer specific enough for logging it in our history.

Is there an existing option to reward a piece of loot with a custom reasoning, that gets placed as &r - on an occasion-by-occasion (example, "Reward" > "Custom") somehow I've missed? Or would this be a possible addition.

Let me know if I need to clarify, or if the request simply doesn't make sense for the addon's purpose. I know we're using it quite liberally as we don't as much run a council, as we let rolls and preset priorities play into the choices submitted by our raiders.

Best Regards
Christian

**Comment by evil-morfar** [comment]
Not quite sure I follow you - all the responses (including the [award reasons](https://github.com/evil-morfar/RCLootCouncil2/wiki/Options#award-reasons)) are [customizeable](https://github.com/evil-morfar/RCLootCouncil2/wiki/Options#buttons-and-responses).
