### ISSUE TITLE
Vote Window Order

### ISSUE THREAD

**Issue by Psypherlol** [evil-morfar/RCLootCouncil_Classic#18]
Per discord request: Saved Variables. I copied them to a word file because .lua is not supported by github for attachments.

[RCLootCouncilDB.docx](https://github.com/evil-morfar/RCLootCouncil_Classic/files/4466880/RCLootCouncilDB.docx)

**Comment by evil-morfar** [comment]
There's seems to be an issue with the move up/down buttons in the options menu.

For now, a quick fix on your end is to edit the lua file and change the sort numbers in it while the game is closed. Do a search for `["text"] = "Best in Slot",` and change the `["sort"]` value for each of  the responses.

**Comment by Psypherlol** [comment]
Seems to be working after doing that. Thanks.
