### ISSUE TITLE
Adding item types to certain council members.

### ISSUE THREAD

**Issue by karyzan** [evil-morfar/RCLootCouncil_Classic#19]
I'm sorry for posting this as an issue but last time you were very quick to reply and solved it just as fast! Thank you!

I just want to know if it's possible to add certain item types for different council members.

Example:
Player1 - Mail - Weapons 
Player2 - Leather - Weapons
Player3 - Cloth - Weapons - Miscellaneous(Trinket, Neck, Back)

This would be an amazing feature and would help a lot with councils that have members doing different things. Thanks mate for this addon!

**Comment by evil-morfar** [comment]
It's fine, Github issues is the right place to do requests as well :)

So you basically want certain council members to only see certain items?

This would require a massive amount of work on my end for something that's basically a niche thing, and can be accomplished by agreeing with each council member what their role in the council is. 
While it's possible to do, I just don't see it being worth the headaches such a feature would require to implement. Thanks for your suggestion though.

**Comment by karyzan** [comment]
> It's fine, Github issues is the right place to do requests as well :)
> 
> So you basically want certain council members to only see certain items?
> 
> This would require a massive amount of work on my end for something that's basically a niche thing, and can be accomplished by agreeing with each council member what their role in the council is.
> While it's possible to do, I just don't see it being worth the headaches such a feature would require to implement. Thanks for your suggestion though.

Yeah that's what I wanted. 
Just wanted this so it would be less items for the council to go trough when the loot is handled all at the same time after last boss. But yeah if it takes long time to add then it's not worth the trouble. 
Thanks anyways and thanks for this amazing addon :)
