### ISSUE TITLE
Resto Shaman shouldn't autopass cloth

### ISSUE THREAD

**Issue by kayti-wow** [evil-morfar/RCLootCouncil_Classic#2]
Apart from tier gear, there's very little good healing gear that is mail.  Shaman should have the option to request cloth gear.

**Comment by evil-morfar** [comment]
I'll disable auto passing by default next update.

I have no way of detecting which spec a player is "in", thus can only use the class to do auto passes - in which case it's better not to have it. You can disable auto passes already though.

**Comment by evil-morfar** [comment]
Fixed in v0.2.0. Thanks for your report.
