### ISSUE TITLE
Session creation times out

### ISSUE THREAD

**Issue by anthares** [evil-morfar/RCLootCouncil_Classic#21]
Hi there :)

Last night we faced an issue during our MC run.

To save some time, I'm used to award loots from several bosses in bunches.
Yesterday, I had enough space to keep loots from the four first bosses in my bag, a total of 10 items.

But when I started a session to award them, the roll windows never appeared.
After a few minutes, I tried a reloadui, and the addon told me in needs to sync data for the rest of the night.
I already noticed some delays when starting a session, but never that long.

I don't understand if I doing something wrong, or if there was an external issue, but ping was okay and my PC was almost idling.

How my I assist you to debug this issue, which is quite annoying ? (logs, testing, ...)
Did I something wrong ? too many items ? or maybe some issues in how data are shared between members of the raid ?

Anyway, this is the first time I face a blocking issue with this addon, so congrats for this neat piece of software :)

Regards,

Nicolas

**Comment by evil-morfar** [comment]
Thanks for your report.
I have enough info from other reports to go forward on.

The issue happens when the ML does a /reload and no changes to the group happens before a session.

**Comment by anthares** [comment]
Ok, thank you for your answer, this explains why it stopped working after the /reload :)

But what about the session that doesn't start 10 items before the /reload ?
I don't know how data is shared between players (some kind of data broker, I suppose), but can it be tied to blizzard's servers load ?

Regards,
Nicolas

**Comment by evil-morfar** [comment]
Ah kinda missed that point.
Did you see any chat outputs or anything else while waiting?

**Comment by evil-morfar** [comment]
I'll probably need your saved variables to investigate it - it's located at `.../World of Warcraft/_classic_/WTF/Account/"account_name"/SavedVariables/RCLootCouncil_Classic.lua`.

**Comment by middreks** [comment]
We had the same issue tonight both with 0.9.1 and 0.9.2.
For a while it worked with /rc add for me, then we went to MC and Ony and we couldn't use it anymore at all.
Either via autoloot or via /rc add it just added a message about waiting sync to finish. Did /reload and relog, neither helped.
Attached saved variables to help debugging this.
[RCLootCouncil_Classic.zip](https://github.com/evil-morfar/RCLootCouncil_Classic/files/4664626/RCLootCouncil_Classic.zip)

**Comment by anthares** [comment]
Hey,

Here are what you requested. Hope it will help :)
I didn't noticed any usual messages.

Best regards,
Nicolas

[RCLootCouncil_Classic.zip](https://github.com/evil-morfar/RCLootCouncil_Classic/files/4668271/RCLootCouncil_Classic.zip)

**Comment by evil-morfar** [comment]
v0.10.0 should fix it - please report back otherwise, and thanks again for your report.
