### ISSUE TITLE
Stuck on Waiting for syncronization RC Loot window

### ISSUE THREAD

**Issue by DigiR1** [evil-morfar/RCLootCouncil_Classic#22]
Waiting for syncronization message apears in chat, however no window pops up to enable loot council. Is this some addon conflict? Have had guild members update to 0.9.3 but no luck.

**Comment by evil-morfar** [comment]
It's caused by an undocumented hotfix to comms Blizzard pushed. I'm looking into a solution.

**Comment by wlfbck** [comment]
@evil-morfar Just out of curiosity, what did they do exactly?

**Comment by evil-morfar** [comment]
I'm not entirely sure of the specifics yet, but evidence points to a throttle silently discarding all messages beyond 10 per second.

**Comment by evil-morfar** [comment]
v0.10.0 should fix it, please report baak otherwise and thanks for your report.
