### ISSUE TITLE
v0.10.0 constant errors

### ISSUE THREAD

**Issue by themegosh** [evil-morfar/RCLootCouncil_Classic#23]
After updating to v0.10.0 today I'm receiving constant errors:

Date: 2020-06-01 18:44:51
ID: 9
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua line 56:
   Error decompressing: ^1^SverTestReply^T^N1^SLopes-Netherwind^N2^SWARLOCK^N3^SCore~`Raider^N4^S0.9.3^N6^T^N1^SRCLootCouncil_Classic~`-~`0.9.3^N2^SRCLootCouncil~`Core~`-~`2.19.1^t^t^^
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:733:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693
   (tail call): ?
   [C]: error()
   ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua:56:
      ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua:52
   ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua:61:
      ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua:60
   ...nterface\AddOns\RCLootCouncil_Classic\Core\Comms.lua:85: ?()
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...Ons\ElvUI\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua:264:
      ...Ons\ElvUI\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.7 
  AddOnSkins, v4.40
  AdiBags, vDEV
  AdvancedInterfaceOptions, v1.3.4
  AQWarEffort, v
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AtlasLootClassicMaps, vv1.0.0
  ColoredInventoryItems, v1.4
  DBMCore, v1.13.47
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dismounter, v1.2.1
  DRList10, vv1.1.2
  ElvUI, v1.24
  Examiner, vClassic Fan Update (1.09.2)
  ExtendedCharacterStats, v2.4.4
  FADEWorldTimers, v1.0
  FarmHud, v8.3-6-classic-release
  GatherMate2, v1.45.5
  InFlightLoad, v1.13.005
  ItemAutocomplete, v1.0.6
  ItemRack, v
  kgPanels, v1.24
  LeatrixMaps, v1.13.65
  LeatrixPlus, v1.13.65
  LibSharedMedia30, v3.0-113
  LibStub, v
  LightHeaded, vv11302-1.0.0
  LoseControl, v1.05
  NovaWorldBuffs, v1.60
  OmniBar, vv10.8
  OmniCC, v8.3.5
  Parrot, vv2.1-classic2
  PitBull4, vv4.1-classic20
  Plater, vPlater-1.13.4-Classic
  Prat30, v3.8.5
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Questie, v5.10.3
  QuestLogEx, v1.2
  RCLootCouncilClassic, v0.10.0
  Recount, vv1.13.4b
  ServerFriendsOnly, v1.1.14
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.28
  Stubby, v8.2.6510 (SwimmingSeadragon)
  ThreatClassic2, v2.19
  TinyTooltip, v8.2.1
  TradeSkillMaster, vv4.9.35
  TradeSkillMasterAppHelper, vv4.0.8
  unitscan, v1.0.0
  WeakAuras, v2.17.5
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=5d8)

**Comment by evil-morfar** [comment]
See https://www.curseforge.com/wow/addons/rclootcouncil-classic?comment=303
