### ISSUE TITLE
The amount of LUA Errors popping up is insane

### ISSUE THREAD

**Issue by whyudothis5656** [evil-morfar/RCLootCouncil_Classic#24]
Every 2 seconds an error pops up and you cant get rid of them by turning lua errors off.

**Comment by evil-morfar** [comment]
Or have people upgrade. See https://www.curseforge.com/wow/addons/rclootcouncil-classic?comment=303

**Comment by d07RiV** [comment]
Addons shouldn't be spamming errors because of other players, though.
