### ISSUE TITLE
Distributing AQ40 mounts

### ISSUE THREAD

**Issue by Orphis** [evil-morfar/RCLootCouncil_Classic#31]
It would be great if RCLC would help for distributing mounts.
I was thinking of an auto-pass filter for colors you already have and possibly listing colors people have in their inventory in the voters window.
That would definitely help distributing mounts to people without one first and then colors to people to want to collect them quickly.

Is this possible in the current framework or too different from other items since that would require looking in the inventory?

**Comment by evil-morfar** [comment]
I'm not sure if you're requesting that RCLootCouncil should handle mounts in general (which it can) or just the different colors. 
As for the colors thing, I'm gonna pass on that. It doesn't really fit in with the current design constraints, and is too much work for too little gain imo. 

Thanks for the suggestion though.

**Comment by Orphis** [comment]
It's not just the color, it's also reporting automatically which one(s) you have in your inventory to quickly identify who has a mount and who doesn't to speed up distribution.

**Comment by evil-morfar** [comment]
Maybe I should have elaborated.
It's the inventory scanning in general that's problematic - not to mention the current system can only show two items per player in the voting frame. Also, what would happen if someone banked the mount?

Second issue is, if I did it for classic, I'd have to do it in retail as well, which means creating two wastly different systems.

All in all I have too many things on my todo list that I deem a better use of my time.
