### ISSUE TITLE
RCLC-Classic doesn't work on WOTLK-Classic version of the game.

### ISSUE THREAD

**Issue by Beeblespark** [evil-morfar/RCLootCouncil_Classic#38]
Title says it all.

**Comment by Jorvanus** [comment]
Yeah, it's discussed in your Disc, new patch from blizzard means it doesn't load.

**Comment by jasskin** [comment]
Date: 2022-09-03 19:25:32
ID: 1
Error occured in: Global
Count: 1
Message: ...ootCouncil_Classic\RCLootCouncil\Modules\TradeUI.lua line 71:
   attempt to index field 'frame' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=(tail call)"]: ?
   [string "@RCLootCouncil_Classic\RCLootCouncil\Modules\TradeUI.lua"]:71: Hide()
   [string "@RCLootCouncil_Classic\RCLootCouncil\Modules\TradeUI.lua"]:57:
      ...ootCouncil_Classic\RCLootCouncil\Modules\TradeUI.lua:55
   [string "=[C]"]: ?
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:562: DisableAddon()
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:574:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:555
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: EnableAddon()
   [string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  WowheadLooter, v20504
  Atlas, vv1.51.06
  AtlasBurningCrusade, vv1.51.02
  AtlasClassicWoW, vv1.51.02
  AtlasLootClassic, vv2.4.4-bcc
  AtlasLootClassicData, vv2.4.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.4-bcc
  ATTClassic, v1.0.5
  Attune, v304
  AucAdvanced, v3.4.6777 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  AutoLoggerClassic, vv1.7.1-classic-release
  BagBrother, v
  Bagnon, v9.2.1
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  BuffomatClassic, v2022.7.5-84ffbcc3
  BuffomatClassicTBC, v2022.7.1
  DBMCore, vd87d644
  DBMStatusBarTimers, vd87d644
  DBMVPVEM, v6746e8a
  DejaClassicStats, v30400r2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v3.00
  Enchantrix, v3.4.6812 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  GatherMate2, v1.46.1-classic
  GuildRosterManager, v1.92991
  ItemRack, v
  LeatrixMaps, v3.0.05
  LeatrixPlus, v3.0.02
  Ogrilastone, v1.5
  OmniCC, v9.2.1
  Questie, v7.0.1
  RareScanner, v3.4.0
  RatingBuster, v
  RCLootCouncilClassic, v0.14.1
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  StatLogic, v
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v10.5.0
  TomTom, vv3.1.4
  TradeSkillMaster, vv4.11.44
  TradeSkillMasterAppHelper, vv4.0.23
  VuhDo, v3.137-tbcc
  VuhDoOptions, v3.137-tbcc
  WeakAuras, v4.1.2
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=6e6)

**Comment by sofar** [comment]
A fix / workaround is suggested by a curseforge user here:

https://www.curseforge.com/wow/addons/rclootcouncil-classic?comment=503

**Comment by Jorvanus** [comment]
> A fix / workaround is suggested by a curseforge user here:
> 
> https://www.curseforge.com/wow/addons/rclootcouncil-classic?comment=503

Saw that, not exactly practical for the entire guild to have to do this.

**Comment by evil-morfar** [comment]
Fixed with #37

**Comment by Jorvanus** [comment]
> Fixed with #37

@evil-morfar Awesome. Odds of pushing it out for release so Curseforge picks it up:?

**Comment by sfjuocekr** [comment]
Using the fixed version we are getting:

```
13x RCLootCouncil_Classic\Core\Hooks.lua:70: attempt to concatenate field 'version' (a nil value)
[string "@RCLootCouncil_Classic\Core\Hooks.lua"]:70: in function <RCLootCouncil_Classic\Core\Hooks.lua:67>
[string "=(tail call)"]: ?
[string "@RCLootCouncil_Classic\RCLootCouncil\core.lua"]:695: in function `origHandler'
[string "@RCLootCouncil_Classic\Core\Comms.lua"]:68: in function <RCLootCouncil_Classic\Core\Comms.lua:66>
[string "@RCLootCouncil_Classic\Core\Comms.lua"]:91: in function `?'
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Attune\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:264: in function <...rfaceAttune\Libs\AceComm-3.0\AceComm-3.0.lua:246>
```

everytime someone with the addon comes online.

I looked to the code quickly, but Im not sure why version is nil at that point as it should have been set in function RCLootCouncil:OnInitialize() line 94.

Maybe I'm just overseeing something obvious here.

**Comment by sfjuocekr** [comment]
[RCLootCouncil_Classic.tar.gz](https://github.com/evil-morfar/RCLootCouncil_Classic/files/9499514/RCLootCouncil_Classic.tar.gz)

This should work @Jorvanus it only throws the said error that I linked above.

**Comment by evil-morfar** [comment]
You can't just use the code from here as an addon - it needs to be built first, which has some issues (mainly due to the packager), hence no updated version yet. 
You'd need to insert a version into `./RCLootCouncil/core.lua`  line 94 for it to work.

**Comment by sfjuocekr** [comment]
Ah ok, I'm quite green when it comes to addon development.

I never knew you needed to build anything, all the things I have done for addons were always just edits in text files and that usually works.

Got any documentation or other resources I could read on this build process?

edit: I think I've figured it out, the "build" basically replaces a bunch of strings as noted in replace.sh. I'm on Linux, so I might just update your scripts ;)

**Comment by evil-morfar** [comment]
Depends on the project. Tools such as the bigwigs packager and curseforge packager can modify files depending on keywords, which I don't really use (maybe with the exception of toc interface versions). It's only needed here because the RCLC version is gathered from its TOC, which isn't loaded in classic, but still required for the addon to function. Hence my replacement script.

**Comment by cwilson21** [comment]
A working version with the changes can be temporarily obtained from here: 

https://drive.google.com/drive/folders/190Qg4mvd4hPaPHVKKzgfT2EYH1XhwEdD?usp=sharing

**Comment by ryancole** [comment]
> Depends on the project. Tools such as the bigwigs packager and curseforge packager can modify files depending on keywords, which I don't really use (maybe with the exception of toc interface versions). It's only needed here because the RCLC version is gathered from its TOC, which isn't loaded in classic, but still required for the addon to function. Hence my replacement script.

Are you creating a new release build for curseforge?

**Comment by evil-morfar** [comment]
Yes, CurseForge is still processing it. In the mean time, it's available at https://github.com/evil-morfar/RCLootCouncil_Classic/releases/tag/0.15.0 and https://addons.wago.io/addons/rclootcouncil-classic/versions?stability=stable .
