### ISSUE TITLE
 /rc history not working without /run script as Master Looter

### ISSUE THREAD

**Issue by jtr-dev** [evil-morfar/RCLootCouncil_Classic#4]
I tested this out a bit with this troubleshooting checklist I found: 

``` 
/run RCLootCouncil.nnp = true

/rc test 5

Award all the items to yourself

/rc history *works*

/reload

[repeat actions skipping first step]

/rc history *doesn't work*
``` 

I invited a raid leader to test this with, and tried passing Master Looter, reloading, running the script, and history didn't work.

Tried the same situation with him running the script and history worked for both of us.

**Comment by evil-morfar** [comment]
Would you really want tests to be saved to history? 

It's working as intended, and it will track awards in a real raid. The `.nnp` setting was added for my convenience, and for when I needed an easy way of telling people that the history works.

**Comment by jtr-dev** [comment]
I mean this is my steps for testing. Actual loot history while raiding isn't being saved to history, we've been clearing MC/Ony for weeks now without that feature. 

I pass master looter off to another raid lead, and if they set the flag via `/run RCLootCouncil.nnp = true` it works for everyone in the raid. Previously no one within the raids [40] has working/consistent history.

**Comment by evil-morfar** [comment]
Did you turn off [Enable- or Send History](https://github.com/evil-morfar/RCLootCouncil2/wiki/Options#loot-history)?

If not, then I need your SavedVariables file. Everything works fine for me.

**Comment by jtr-dev** [comment]
Those weren't turned off, I think the issue is there's no file within SavedVariables. 
I believe ACEdb is supposed to create said file?

**Comment by evil-morfar** [comment]
Well, wow creates it, ACEdb is just used to access it and data structure. 

If you're certain the file doesn't exist, then it's most likely a lua error. You can check that with `/console scriptErrors 1`.

**Comment by jtr-dev** [comment]
I'm not sure what this case was, but it's working now, perhaps with a recent update. 😄   There's also a RCLootCouncil_Classic.lua in SavedVariables as well now.

**Comment by evil-morfar** [comment]
Odd. But great that it works.
