### ISSUE TITLE
JSON export missing id

### ISSUE THREAD

**Issue by robertjpayne** [evil-morfar/RCLootCouncil_Classic#43]
Believe the JSON exporter is missing `tinsert(export, string.format("\"%s\":\"%s\"", "id", tostring(d.id)))` for id export.

**Comment by evil-morfar** [comment]
It's not "missing", it just wasn't added (I didn't create the json export). Do you need it?

**Comment by robertjpayne** [comment]
Hey every other export includes that so I just found it weird it wasn't there assumed it was missed (I thought the JSON Export was relatively new sorry if it wasn't!).

I use JSON export to load it into a postgres database and do interesting things, Postgres can parse JSON natively but not CSVs so easily.

I have edited my local addon but just thought I'd add it here.

**Comment by evil-morfar** [comment]
I'll add it next update - anything else you're missing?

**Comment by evil-morfar** [comment]
Also using postgress sounds like you're doing something big, mind me asking what you're doing/building? 😊

**Comment by robertjpayne** [comment]
Not really anything else, I think the only announce in the export is that it can't tag the items to the correct zone/boss if you do all the loot at the end but that is more on Blizzard than yourself I'm finding.

I'm putting together a website for the guild that will make our loot ledger publicly available and browse able by raid/player/item!

**Comment by evil-morfar** [comment]
Huh wasn't aware of that. I can make sure the boss name is retained, but doing the same for zone (and other related data) is a larger undertaking - system wasn't originally build with award later in mind.

Sounds interesting! Is it private or are you able to share some details?

**Comment by robertjpayne** [comment]
Retaining boss name would be huge, zone is easily editable because normally its just one or two instances but that boss name is yea a bit of a stickler. I'll share what I'm doing when it's done, do you have a discord?

**Comment by evil-morfar** [comment]
https://discord.com/invite/WfYhCx9
