### ISSUE TITLE
Head items are shown incorrectly during voting

### ISSUE THREAD

**Issue by Pocokk** [evil-morfar/RCLootCouncil_Classic#44]
Title.

Instead of the regular button texts, it just says "Button" on all the options + when the loot is distributed via MasterLooting, the reason is always "Responses" instead of the set text.

**Comment by evil-morfar** [comment]
Sounds like you've added a new button/response group for head pieces without editing the default text.

Check your buttons and responses settings (`/rc c`).

**Comment by Pocokk** [comment]
Thank you, it is resolved now! We messed it up somehow.
