### ISSUE TITLE
Deathknights not showing up in history or exports

### ISSUE THREAD

**Issue by robbie5656** [evil-morfar/RCLootCouncil_Classic#45]
I'm on version 0.16.1 for wotlk. When I go to /rc history I see all of my guild's loot there except for Deathknights. Additionally, when I export the gear to thatsmybis none of the Deathknights gear shows up on the site, probably b/c it doesn't exist in the history file. A few of my fellow officers can't see Deathknight loot but some of them can, and despite them exporting their loot history to me, I still can't see them. I know this doesn't show much but here is a screenshot showing the loot history for our top dps Deathknight. 
![image](https://user-images.githubusercontent.com/71793533/197096881-330b5eac-cd7e-45c7-9e6b-d639704a73f1.png)

**Comment by evil-morfar** [comment]
Deathknights are being filtered, indicated by the slight color change on the filter button
