### ISSUE TITLE
'ilvl' (a nil value)

### ISSUE THREAD

**Issue by CKNOEP** [evil-morfar/RCLootCouncil_Classic#46]
Hello
Nature doesn't like a vacuum, neither does LUA.
Thank you for your great work, I like it very much
------------------------------------------------------------------------------

3x RCLootCouncil_Classic\RCLootCouncil\core.lua:1344: attempt to perform arithmetic on local 'ilvl' (a nil value)
[string "@RCLootCouncil_Classic\RCLootCouncil\core.lua"]:1344: in function `GetIlvlDifference'
[string "@RCLootCouncil_Classic\RCLootCouncil\core.lua"]:1506: in function `SendLootAck'
[string "@RCLootCouncil_Classic\RCLootCouncil\core.lua"]:755: in function `origHandler'
[string "@RCLootCouncil_Classic\Core\Comms.lua"]:93: in function <RCLootCouncil_Classic\Core\Comms.lua:87>
[string "@RCLootCouncil_Classic\Core\Comms.lua"]:117: in function `?'
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@BugSack\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:260: in function <...faceBugSack\Libs\AceComm-3.0\AceComm-3.0.lua:242>

**Comment by evil-morfar** [comment]
Thanks for the report. Not really sure how that can happen, as it would require an item in session to somehow not have an ilvl, which should be impossible. 
Either way I've added a check for it.
