### ISSUE TITLE
Auto-trade not working

### ISSUE THREAD

**Issue by robertjpayne** [evil-morfar/RCLootCouncil_Classic#47]
I can try to provide you as much info as I can. But last night the auto-trade window would show sometimes but it never worked, tried restarting WoW, reloading, making sure everyone had updated but no dice.

Let me know if there is any sort of tests/logs I can provide.

**Comment by evil-morfar** [comment]
Please attach your SV located at `../World of Warcraft/_classic_/WTF/Account/account_name/SavedVariables/RCLootCouncil_Classic.lua`

**Comment by robertjpayne** [comment]
I put in discord issues channel!
