### ISSUE TITLE
Feature Request: Sort or Filter History by Class

### ISSUE THREAD

**Issue by kayti-wow** [evil-morfar/RCLootCouncil_Classic#5]
I like to view the loot history before casting a vote, but it can be hard to compare raid members when you can't narrow down the view to a particular class.

**Comment by evil-morfar** [comment]
I may consider it for the future, but it's quite cumbersome to add more to the history. Do note you can use the more info tooltip on the voting frame to see recent items, and if you keep your history clean, you could skip opening the loot history entirely.

**Comment by evil-morfar** [comment]
Class sorting is added in v0.5.0. I plan to do an update on the filters at a later date and will include the classes as a filterable.
