### ISSUE TITLE
Request: csv export with european seperator

### ISSUE THREAD

**Issue by Raistlin1990** [evil-morfar/RCLootCouncil_Classic#50]
Hiho,
I'm trying to automate the csv export. Europe uses a different seperator for the coloums (;) as the US (,). 
Is there a way to implement that in the export option?

Thanks!

**Comment by evil-morfar** [comment]
That's not strictly true. While it's common in Europe to use semi colons, it doesn't change the fact that CSV is *comma* separated values. I've also never seen a program that can't handle commas. You can also use the TSV export, which Excel defaults to.

If there's *really* no way you can consume the data, then I'll create a semicolon separated export similar to the current CSV.
