### ISSUE TITLE
Voting frame bugged out when I logged in

### ISSUE THREAD

**Issue by Pocokk** [evil-morfar/RCLootCouncil_Classic#52]
I was just about to log in, when the loot master announced the items/the voting frame popped up, but it was empty for me. 

Afterwards I was getting these strange errors occasionally:

28x ...ouncil_Classic/RCLootCouncil/Modules/votingFrame.lua:532: attempt to index field '?' (a nil value)
[string "@RCLootCouncil_Classic/RCLootCouncil/Modules/votingFrame.lua"]:532: in function `Update'
[string "@RCLootCouncil_Classic/RCLootCouncil/Modules/votingFrame.lua"]:144: in function `EndSession'
[string "@RCLootCouncil_Classic/RCLootCouncil/core.lua"]:777: in function `origHandler'
[string "@RCLootCouncil_Classic/Core/Comms.lua"]:93: in function <RCLootCouncil_Classic/Core/Comms.lua:87>
[string "@RCLootCouncil_Classic/Core/Comms.lua"]:117: in function `?'
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@BugSack/Libs/AceComm-3.0-12/AceComm-3.0.lua"]:260: in function <...faceBugSack/Libs/AceComm-3.0/AceComm-3.0.lua:242>

**Comment by evil-morfar** [comment]
Should be fixed in later versions. Sorry for not getting back too you, and thanks for the report.

**Comment by Pocokk** [comment]
Thank you.
