### ISSUE TITLE
WOTLK ICC PTR ERRORS

### ISSUE THREAD

**Issue by Jorvanus** [evil-morfar/RCLootCouncil_Classic#54]
I know it's PTR, but just thought I'd throw up some advanced notice of a few errors on there.  

![image](https://github.com/evil-morfar/RCLootCouncil_Classic/assets/89010934/6b085aa1-b569-4ce0-98de-07aef6a3a80d)

![image](https://github.com/evil-morfar/RCLootCouncil_Classic/assets/89010934/24562574-f68c-476e-bfb1-73c30aaaa9e4)

![image](https://github.com/evil-morfar/RCLootCouncil_Classic/assets/89010934/8210b81c-85f9-41e2-9198-a1b10fbbf7bb)

**Comment by evil-morfar** [comment]
Both the top errors are related to the bottom one, which is most likely already fixed in newer Ace3 versions - i.e. you can try installing Ace3, or update the one contained in RCLC.

Thanks for the warning though

**Comment by Jorvanus** [comment]
> Both the top errors are related to the bottom one, which is most likely already fixed in newer Ace3 versions - i.e. you can try installing Ace3, or update the one contained in RCLC.
> 
> Thanks for the warning though

Didn't need to use it, so didn't bother with getting or checking on Ace3.  But ICC drops next week FYI.
