### ISSUE TITLE
[Feature Request] Expand "Advanced Auto Pass" to include Item Subtypes or Item Stats

### ISSUE THREAD

**Issue by Kolmarwow** [evil-morfar/RCLootCouncil_Classic#58]
Currently under "Advanced Auto Pass" you can select item slots such as head/neck/etc, which is a bit limited imo. I think it'd be neat to expand this to include item subtypes such as cloth/leather/swords/etc. Would be useful as a warrior where i "can" wear cloth/staves but will realistically never use them, you can get locale-independent values from the 12th+13th return of [GetItemInfo](https://warcraft.wiki.gg/wiki/API_C_Item.GetItemInfo).

Alternatively you can get locale-independent stats through [GetItemStats](https://warcraft.wiki.gg/wiki/API_GetItemStats) which would be useful for autopassing primary stats you don't care about like agility/intellect for warriors, it also includes secondary stats but that might be too troublesome to keep consistent across all game versions (especially when classic era can't retrieve crit/hit due to vanilla not using the rating system).

Addon version: 0.22.7
Game Version: Cataclysm Classic 4.4.0

**Comment by evil-morfar** [comment]
I'm not sure if I want to add 20 weapons + 11 armor types - that would *really* clutter the menu. I didn't even want to add the current "Advanced Auto Pass", but someone else made it, and it did no harm.

In Cataclysm warriors should already be auto passing non plate items, and the question really is why things like staves isn't included in the auto pass list for classes that won't be using it. That's a much cleaner and simpler implementation.

Auto passing non main stat is already a thing in the retail version, which will come for Classic once I get done porting v3.x.

**Comment by Kolmarwow** [comment]
ah good, that does sound a lot better. i thought it wasn't auto-passing non-plate as i remembered some cloth/leather items showing up but now i think those items were BoE while BoP items are being autopassed, i'll pay more attention to it in my raid tomorrow.

edit: yep it's correctly passing all BoP non-plate loot, so it's already working like I wanted and I just didn't notice :) whoops.
