### ISSUE TITLE
Version warning

### ISSUE THREAD

**Issue by ddiava** [evil-morfar/RCLootCouncil_Classic#7]
Version was updated to from "2.14.0" to "2.15.1"
An update/modif to https://github.com/evil-morfar/RCLootCouncil_Classic/commit/c4ce66527c23cf6bfb78f101250ca690699b9c09 is needed

**Comment by evil-morfar** [comment]
It's not that simple. After v0.3.0 the core RCLootCouncil version should not be sent, so the only real reason this could be happening is if someone has installed the retail version - which in itself doesn't run on Classic.

**Comment by evil-morfar** [comment]
Well, turns out not being in a guild in Classic was the real issue. https://github.com/evil-morfar/RCLootCouncil2/commit/9f99b8cfcedd40d2a4163f2ab3baa458e68bb058 - thanks for your report.
