### ISSUE TITLE
release script, missing tags in submodule

### ISSUE THREAD

**Issue by ddiava** [evil-morfar/RCLootCouncil_Classic#8]
Comparing the version 0.4.1 you just released and the git source code, I saw that the release scripts is modifing core.lua with "2.14.0".
tags 2.15.x are missing in the submodule, or at least they are not reachable from the branch and latest found is 2.14.0
"git -C ./RCLootCouncil describe --tags --always --abbrev=0" still reports 2.14.0

it may be related to https://github.com/evil-morfar/RCLootCouncil_Classic/issues/7 and the commit i was pointing to.

**Comment by ddiava** [comment]
Tags 2.15.0-Release and 2.15.1-Release do exist.
It looks like the tag "2.14.0-Release" was set on the develop branch and is the only one in this case, for the few ones i checked

**Comment by evil-morfar** [comment]
Ah well. I suppose that's the downside of pushing from the development branch instead of master. 

All the changes are included, it's just the tag that's missing, meaning the core RCLC version will be listed as 2.14.0 in game - I suppose we can live with that.
